#!/bin/bash
docker run -it --rm -v .:/code robindiddams/nasm-toolchain nasm -f bin /code/src/boot.asm -o "/code/.out/boot.bin"
docker run -it --rm -v .:/code robindiddams/nasm-toolchain nasm -f elf64 /code/src/kernel/entry.asm -o "/code/.out/kernel-entry.o"
make
python make-iso.py
